### ISSUE TITLE
IKON Multitouch prototype

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-projektor#157]
- [ ] integrate hammer.js into stable release
-- [ ] integrate solutions from proof-of-concept
- [ ] check possible extensions
-- [ ] component zoom: cluster = classic zoom, timeline = compress/extend x-scale
-- [ ] extend components in size
-- [ ] show selection details in movable overlay

**Comment by mx-e** [comment]
this is a very large ticket (1500+ changes estimated)
Therefore I would recommend focusing on movable overlays in a separate ticket because:
- hammer js likely does not work with react (synthetic events etc.)
- I will need a few more days to integrate a touch prototype into master, which can then be extended
