### ISSUE TITLE
IKON State Management & Sharing

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-projektor#163]
- [ ] improve performance of state "fixity", especially when something (e.g., a project, a target group etc.) is selected in the visualization
- [ ] research encoding state into minified URL for sharing, or "key"
- [ ] implement sharing interface (see attached image) with "copy to clipboard" function

**Comment by jessebenjamin** [comment]
![projektor-share](https://user-images.githubusercontent.com/5793149/72976326-ad693080-3dd2-11ea-89b0-3ec32b198926.jpg)

**Comment by mx-e** [comment]
It is merged in master after code review, as we are in a bit of a hurry. Please conduct functional review ASAP and put any bugs/remaining issues into a new ticket. 
Encoding is BASE64 btw, im pretty sure it is the shortest not using any escape characters (i.e. suitable for URL use), the string is VERY long.
If we want to have a shorter string we need to do FrontEnd based mappings for filter values, which is not great since the app then basically has some of the data loaded from the backend hardcoded into it.

**Comment by mx-e** [comment]
@jessebenjamin
