### ISSUE TITLE
Integrate Browser-/Touch-Version

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-projektor#194]
The goal is that both versions are hosted at the MfN.

- [x] create workable flag that distinguished btw serving browser- and touch-versions
- [x] test robustness of method

**Comment by mx-e** [comment]
there is no way to reliably distinguish between displays with/without touch support in browser for multiple browsers / platforms

the standard approach would be to implement handlers for both event types.
however, we serve a completely different app (layout, components) to the touch displays
you would not for example want to display the touchscreen version of the app on a Surface Tablet, just because it supports touch. 

one could use a /touch url extension to manually switch between versions
this would however be publicly usable

**Comment by mx-e** [comment]
how do we go ahead ?

**Comment by wittenator** [comment]
In my opinion it is not too bad, that it is publicly available. The only question is whether we implement the router split logic in react or in Nginx

**Comment by mx-e** [comment]
to implement it in react would result in a more maintainable code base. However, depending on how much legacy code would need to be improved to handle the level of flexibility required, it might not be worth the effort. I'll get back to you on this, after taking a look at the current diff (few days, few other tickets ahead) 

For now do @jessebenjamin @ckinkeldey agree on using a url extension as a flag ?

**Comment by wittenator** [comment]
Agree on the maintainability 👍

**Comment by jessebenjamin** [comment]
yes url-extension
