### ISSUE TITLE
color scheme uncertainty

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/IKON-projektor#236]
If the greyscale of the uncertainty vis is discretized (color steps), the legend must be, too

**Comment by ckinkeldey** [comment]
![Screenshot 2020-04-29 14 07 16](https://user-images.githubusercontent.com/3234376/80594370-2657d400-8a23-11ea-94f9-f2083d276d70.png)

**Comment by ckinkeldey** [comment]
Is thre a reason for the discrete color scheme? Can't we switch back to the continuous scheme?

**Comment by lillijo** [comment]
it is just more computation heavy because we are kind of creating artificial sublevels. but I tried it out, it seems to not really be a problem to increase the number of bins:
(there is still discretization, but I guess this is smooth enough?) 

![Screenshot from 2020-04-29 15-17-19](https://user-images.githubusercontent.com/38139300/80600344-8bfc8e00-8a2c-11ea-93c8-35e8d115af99.png)

**Comment by lillijo** [comment]
a bit less smooth: 
![Screenshot from 2020-04-30 12-13-56](https://user-images.githubusercontent.com/38139300/80700574-3aacd700-8ade-11ea-9558-99594b5352cc.png)

**Comment by lillijo** [comment]
this is the default: 
![Screenshot from 2020-04-30 12-30-28](https://user-images.githubusercontent.com/38139300/80700679-6b8d0c00-8ade-11ea-8d07-b8f4e04d319e.png)
