### ISSUE TITLE
Preparation for first visualisation prototype:

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-projektor#34]
- [x] upload projects.json to https://github.com/FUB-HCC/IKON-backend/blob/master/src/rpcserver/nlp/Topic%20extraction.ipynb
- [x] get projects.json working for prototype
- [x] ALL: handover prototype: what's the structure, flags, conventions etc

**Comment by jessebenjamin** [comment]
hey, the jupyter notebook is still not working for me?

**Comment by wittenator** [comment]
Did you install the pipenv packages and start it in pipenv shell? (I need to write a separate Readme for this part)

**Comment by wittenator** [comment]
BTW: I didn't unassign anybody.

**Comment by simon991** [comment]
I did some debugging regarding the 2nd point (get projects.json working for prototype) and I found two issues. So far I was able to solve the first one (I created a new branch to resolve the issue: [https://github.com/FUB-HCC/IKON-projektor/compare/New_dataset](https://github.com/FUB-HCC/IKON-projektor/compare/New_dataset )):
1. Look at the [utility file](https://github.com/FUB-HCC/IKON-projektor/blob/master/src/store/utility.js) of the IKON-projector. Since the sponsor in the new dataset is always the same, the following code results in "urlData.s.map is not a function":
 `` urlData.s ? newUrlData.s = urlData.s.map(s => { return sponsorIntToString(newState, s) }) : newUrlData.s = newState.filter[2].value
``
This is because after the first rendering, the URL gets updated with the current filter. Since the filter for "s" isn't an array anymore but a single value instead, the error occurs. Find my fix here: [https://github.com/FUB-HCC/IKON-projektor/commit/29a99cf7cd9df84e91c463b28129d4f708b00e52](https://github.com/FUB-HCC/IKON-projektor/commit/29a99cf7cd9df84e91c463b28129d4f708b00e52)

2. Furthermore, the [utility file](https://github.com/FUB-HCC/IKON-projektor/blob/master/src/store/utility.js) in the IKON-projector currenty maps topics and flields using a hard coded array. I am not sure how to proceed with this, since in my opinion hard coded mappings don't make much sense. But maybe in this stage of development, it would be the easiest for now to extend the mapping by the values from the new dataset and leave the rest for the time when we integrate the backend? What is your opinion, @wittenator and @jessebenjamin. 
```javascript
// field colors
const fieldsMapping = [
  {name: 'Evolution und Geoprozesse', field: 1, color: '#7d913c'},
  {name: 'Sammlungsentwicklung und Biodiversitätsentdeckung', field: 2, color: '#d9ef36'},
  {name: 'Digitale Welt und Informationswissenschaft', field: 3, color: '#8184a7'},
  {name: 'Wissenskommunikation und Wissensforschung', field: 4, color: '#ed9798'}
]

// topic(hauptthema) colors
const topicMapping = [
  {name: 'Wissenschaftsdatenmanagement', num: '1', field: 3, color: '#8184a7'},
  {name: 'Biodiversitäts- und Geoinformatik', num: '2', field: 3, color: '#8184a7'},
  {name: 'Perspektiven auf Natur - PAN', num: '3', field: 4, color: '#ed9798'},
  {name: 'Historische Arbeitsstelle', num: '4', field: 4, color: '#ed9798'},
  {name: 'Sammlungsentwicklung', num: '5', field: 2, color: '#d9ef36'},
  {name: 'Wissenschaft in der Gesellschaft', num: '6', field: 4, color: '#ed9798'},
  {name: 'Bildung und Vermittlung', num: '7', field: 4, color: '#ed9798'},
  {name: 'Evolutionäre Morphologie', num: '8', field: 1, color: '#7d913c'},
  {name: 'Ausstellung und Wissenstransfer', num: '9', field: 4, color: '#ed9798'},
  {name: 'Mikroevolution', num: '10', field: 1, color: '#7d913c'},
  {name: 'Impakt- und Meteoritenforschung', num: '11', field: 1, color: '#7d913c'},
  {name: 'Diversitätsdynamik', num: '12', field: 1, color: '#7d913c'},
  {name: 'Biodiversitätsentdeckung', num: '13', field: 2, color: '#d9ef36'},
  {name: 'IT- Forschungsinfrastrukturen', num: '14', field: 3, color: '#8184a7'},
  {name: 'Kompetenzzentrum Sammlung', num: '15', field: 2, color: '#d9ef36'}
]

export const fieldsIntToString = (number) => {
  number = parseInt(number, 10) // pls fix
  return fieldsMapping.find(e => e.field === number) ? fieldsMapping.find(e => e.field === number).name : number
}

export const fieldsStringToInt = (str) => {
  return fieldsMapping.find(e => e.name === str) ? fieldsMapping.find(e => e.name === str).field + '' : str
}

export const topicIntToString = (number) => {
  return topicMapping.find(e => e.num === number) ? topicMapping.find(e => e.num === number).name : 'Other'
}

export const topicStringToInt = (str) => {
  return topicMapping.find(e => e.name === str) ? topicMapping.find(e => e.name === str).num : str
}
```

**Comment by simon991** [comment]
Some more notes:
2.1 
In the old dataset the _forschungsbereich_ property (_fields_ in the utility.js) was represented by a number, now it is a string.

2.2
The _hauptthema_ property (_topic_ in the utility.js) is still a string, same as before, but additional entries need to be added to the _topicMapping_

**Comment by simon991** [comment]
I addressed the 2nd issue in this commit [https://github.com/FUB-HCC/IKON-projektor/commit/22c006b897372145341e3d3bcd1f146a220bdcc1](https://github.com/FUB-HCC/IKON-projektor/commit/22c006b897372145341e3d3bcd1f146a220bdcc1):

I extended the topicMapping as well as the fieldsMapping and made some changes because the forschungsbereich in the new dataset is now represented by a string instead of a number.

**Comment by jessebenjamin** [comment]
Re: 2nd issue; yes I would agree that we address full backend integration when we have the backend. @wittenator @simon991 @polyphem please coordinate this process, so we do not have "blockages" or redundancies.

**Comment by wittenator** [comment]
@simon991 Cool that you debugged this!
I share your view that this doesn't make sense in the long run. The team which developed the prototype had tight constrains time-wise. That's why some of these solutions seem a bit hack-y. Despite the question if there is a backend or not, I think it would be cool to generate these properties dynamically. Probably depends on how much work you think that is.
